const HEALTH_RECORD_TYPES = {
  MEAL: "meal",
  WATER: "water",
  URINE: "urine",
  FECES: "feces",
  ACTIVITY: "activity",
  WEIGHT: "weight",
  SYMPTOM: "symptom",
};

const HEALTH_RECORD_TYPE_LABELS = {
  [HEALTH_RECORD_TYPES.MEAL]: "식사",
  [HEALTH_RECORD_TYPES.WATER]: "음수",
  [HEALTH_RECORD_TYPES.URINE]: "소변",
  [HEALTH_RECORD_TYPES.FECES]: "배변",
  [HEALTH_RECORD_TYPES.ACTIVITY]: "활동량",
  [HEALTH_RECORD_TYPES.WEIGHT]: "체중",
  [HEALTH_RECORD_TYPES.SYMPTOM]: "증상",
};

module.exports = {
  HEALTH_RECORD_TYPES,
  HEALTH_RECORD_TYPE_LABELS,
};
